// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./components/molecules/Banner.vue')['default']
    Button: typeof import('./components/atoms/Button.vue')['default']
    Card: typeof import('./components/molecules/Card.vue')['default']
    Footer: typeof import('./components/organisms/Footer.vue')['default']
    Grid: typeof import('./components/organisms/Grid.vue')['default']
    Header: typeof import('./components/organisms/Header.vue')['default']
    Link: typeof import('./components/atoms/Link.vue')['default']
    Links: typeof import('./components/molecules/Links.vue')['default']
    Logo: typeof import('./components/atoms/Logo.vue')['default']
    README: typeof import('./components/atoms/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TemplateDefault: typeof import('./components/templates/TemplateDefault.vue')['default']
    Text: typeof import('./components/atoms/Text.vue')['default']
    Title: typeof import('./components/atoms/Title.vue')['default']
  }
}

export {}
